openapi: 3.0.0
info:
  version: '1.0'
  title: 'Space Launch API'
servers:
  - url: 'localhost:3001'
paths:
  /launch:
    get:
      summary: 'Get a list of all launches again and again and again!!'
      operationId: listLaunches
      tags:
        - launch
      parameters:
        - name: id
          in: query
          description: ID of the launch
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a launch by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Launch'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /launch/{id}:
    put:
      summary: 'Update launch information'
      operationId: updateLaunch
      tags:
        - launch
      parameters:
        - name: id
          in: path
          description: ID of the launch
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Launch'
      responses:
        '200':
          description: 'Sample response: The updated launch'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Launch'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Launch:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        launchTimestamp:
          type: string
          format: date-time
        launchLocation:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - LAUNCHED
            - PLANNED
            - SCHEDULED
            - INPROGRESS
            - DEFERRED
            - COMPLETED
            - FAILED
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
